USE [DBHORTI]
GO

/****** OBJECT:  TABLE [DBO].[BAIRRO]    SCRIPT DATE: 23/10/2019 22:59:59 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

EXEC P_REMOVE_FK N'BAIRRO'
GO

IF OBJECT_ID('DBO.BAIRRO', 'U') IS NOT NULL
	DROP TABLE DBO.BAIRRO;

CREATE TABLE [DBO].[BAIRRO](
	[ID_BAIRRO] [UNIQUEIDENTIFIER] NOT NULL,
	[DS_NOME] [VARCHAR](50) NULL,
	[BO_ATIVO] [BIT] NOT NULL CONSTRAINT [C_BAIRRO_ATIVO]  DEFAULT ((1)),
	[DT_CADASTRO] [DATETIME2](3) NOT NULL CONSTRAINT [C_BAIRRO_DT_CADASTRO]  DEFAULT (GETDATE()),
	[DT_ATUALIZACAO] [DATETIME2](3) NOT NULL CONSTRAINT [C_BAIRRO_DT_ATUALIZACAO]  DEFAULT (GETDATE()),
 CONSTRAINT [PK_BAIRRO] PRIMARY KEY CLUSTERED 
(
	[ID_BAIRRO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO