USE [DBHORTI]
GO

/****** OBJECT:  TABLE [DBO].[ESTADO]    SCRIPT DATE: 23/10/2019 22:59:35 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

EXEC P_REMOVE_FK N'ESTADO'
GO

IF OBJECT_ID('DBO.ESTADO', 'U') IS NOT NULL
	DROP TABLE DBO.ESTADO;

CREATE TABLE [DBO].[ESTADO](
	[ID_PAIS] [VARCHAR](5) NOT NULL,
	[ID_ESTADO] [INT] NOT NULL,
	[DS_ESTADO] [NVARCHAR](200) NULL,
	[DS_UF] [VARCHAR](50) NULL,
 CONSTRAINT [PK_ESTADO] PRIMARY KEY CLUSTERED 
(
	[ID_PAIS] ASC,
	[ID_ESTADO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO