USE [DBHORTI]
GO

/****** OBJECT:  TABLE [DBO].[MUNICIPIO]    SCRIPT DATE: 23/10/2019 22:59:01 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

EXEC P_REMOVE_FK N'MUNICIPIO'
GO

IF OBJECT_ID('DBO.MUNICIPIO', 'U') IS NOT NULL
	DROP TABLE DBO.MUNICIPIO;

CREATE TABLE [DBO].[MUNICIPIO](
	[ID_MUNICIPIO] [INT] NOT NULL,
	[ID_PAIS] [VARCHAR](5) NOT NULL,
	[ID_ESTADO] [INT] NOT NULL,
	[DS_MUNICIPIO] [NVARCHAR](200) NULL,
	[CD_MUNICIPIO] [VARCHAR](5) NULL,
 CONSTRAINT [PK_MUNICIPIO] PRIMARY KEY CLUSTERED 
(
	[ID_MUNICIPIO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [DBO].[MUNICIPIO]  WITH CHECK ADD  CONSTRAINT [FK_MUNICIPIO_ESTADO] FOREIGN KEY([ID_PAIS], [ID_ESTADO])
REFERENCES [DBO].[ESTADO] ([ID_PAIS], [ID_ESTADO])
GO

ALTER TABLE [DBO].[MUNICIPIO] CHECK CONSTRAINT [FK_MUNICIPIO_ESTADO]
GO