USE [DBHORTI]
GO

/****** OBJECT:  TABLE [DBO].[PAIS]    SCRIPT DATE: 23/10/2019 22:57:33 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

EXEC P_REMOVE_FK N'PAIS'
GO

IF OBJECT_ID('DBO.PAIS', 'U') IS NOT NULL
	DROP TABLE DBO.PAIS;

CREATE TABLE [DBO].[PAIS](
	[ID_PAIS] [VARCHAR](5) NOT NULL,
	[DS_PAIS] [NVARCHAR](200) NULL,
 CONSTRAINT [PK_PAIS] PRIMARY KEY CLUSTERED 
(
	[ID_PAIS] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO