USE [DBHORTI]
GO

/****** OBJECT:  TABLE [DBO].[PRODUTO]    SCRIPT DATE: 23/10/2019 23:03:04 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

EXEC P_REMOVE_FK N'PRODUTO'
GO

IF OBJECT_ID('DBO.PRODUTO', 'U') IS NOT NULL
	DROP TABLE DBO.PRODUTO;

CREATE TABLE [DBO].[PRODUTO](
	[ID_PRODUTO] [UNIQUEIDENTIFIER] NOT NULL,
	[DS_NOME] [VARCHAR](50) NULL,
	[BO_ATIVO] [BIT] NOT NULL,
	[DT_CADASTRO] [DATETIME2](3) NOT NULL,
	[DT_ATUALIZACAO] [DATETIME2](3) NOT NULL,
	[NM_VALOR] [DECIMAL](12, 2) NOT NULL,
	[NM_DESCONTO] [TINYINT] NULL,
	[DT_DESCONTO] [DATE] NULL,
	[CD_UNIDADE] [UNIQUEIDENTIFIER] NULL,
	[BO_ESTOQUE] [BIT] NOT NULL,
 CONSTRAINT [PK_PRODUTO] PRIMARY KEY CLUSTERED 
(
	[ID_PRODUTO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [DBO].[PRODUTO] ADD  CONSTRAINT [C_PRODUTO_ATIVO]  DEFAULT ((1)) FOR [BO_ATIVO]
GO

ALTER TABLE [DBO].[PRODUTO] ADD  CONSTRAINT [C_PRODUTO_DT_CADASTRO]  DEFAULT (GETDATE()) FOR [DT_CADASTRO]
GO

ALTER TABLE [DBO].[PRODUTO] ADD  CONSTRAINT [C_PRODUTO_DT_ATUALIZACAO]  DEFAULT (GETDATE()) FOR [DT_ATUALIZACAO]
GO

ALTER TABLE [DBO].[PRODUTO] ADD  CONSTRAINT [C_PRODUTO_ESTOQUE]  DEFAULT ((1)) FOR [BO_ESTOQUE]
GO