USE [DBHORTI]
GO

/****** OBJECT:  TABLE [DBO].[PRODUTOR]    SCRIPT DATE: 25/09/2019 19:52:16 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

EXEC P_REMOVE_FK N'PRODUTOR'
GO

IF OBJECT_ID('DBO.PRODUTOR', 'U') IS NOT NULL
	DROP TABLE DBO.PRODUTOR;

CREATE TABLE [DBO].[PRODUTOR](
	[ID_PRODUTOR] [UNIQUEIDENTIFIER] NOT NULL,
	[DS_NOME] [NVARCHAR](100) NOT NULL,
	[BO_ATIVO] [BIT] NOT NULL,
	[DT_CADASTRO] [DATETIME2](3) NOT NULL,
	[DT_ATUALIZACAO] [DATETIME2](3) NOT NULL,
	[DS_NOMEFANTASIA] [VARCHAR](100) NULL,
	[CD_BAIRRO] [UNIQUEIDENTIFIER] NULL,
	[DS_CEP] [CHAR](8) NULL,
	[DS_LOGRADOURO] [NVARCHAR](50) NULL,
	[DS_NUMERO] [VARCHAR](5) NULL,
	[DS_COMPLEMETO] [VARCHAR](15) NULL,
	[DS_INSCRICAOFEDERAL] [VARCHAR](16) NULL,
	[DS_INSCRICAOESTADUAL] [VARCHAR](16) NULL,
	[DS_INSCRICAOMUNICIPAL] [VARCHAR](25) NULL,
	[DS_DESCRICAO] [NVARCHAR](MAX) NULL,
	[DT_NASCIMENTO] [DATE] NULL,
	[DS_EMAIL] [VARCHAR](50) NULL,
	[DS_TELEFONE] [VARCHAR](11) NULL,
 CONSTRAINT [PK_PRODUTOR] PRIMARY KEY CLUSTERED 
(
	[ID_PRODUTOR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [DBO].[PRODUTOR] ADD  CONSTRAINT [C_PRODUTOR_ATIVO]  DEFAULT ((1)) FOR [BO_ATIVO]
GO

ALTER TABLE [DBO].[PRODUTOR] ADD  CONSTRAINT [C_PRODUTOR_DT_CADASTRO]  DEFAULT (GETDATE()) FOR [DT_CADASTRO]
GO

ALTER TABLE [DBO].[PRODUTOR] ADD  CONSTRAINT [C_PRODUTOR_DT_ATUALIZACAO]  DEFAULT (GETDATE()) FOR [DT_ATUALIZACAO]
GO

ALTER TABLE [DBO].[PRODUTOR]  WITH CHECK ADD  CONSTRAINT [FK_PRODUTOR_BAIRRO] FOREIGN KEY([CD_BAIRRO])
REFERENCES [DBO].[BAIRRO] ([ID_BAIRRO])
GO

ALTER TABLE [DBO].[PRODUTOR] CHECK CONSTRAINT [FK_PRODUTOR_BAIRRO]
GO

ALTER TABLE [DBO].[PRODUTOR]  WITH CHECK ADD  CONSTRAINT [C_PRODUTOR_DS_TELEFONE] CHECK  ((NOT [DS_TELEFONE] LIKE '%[^0-9]%') AND (DATALENGTH([DS_TELEFONE]) = 10 OR DATALENGTH([DS_TELEFONE]) = 11))
GO

ALTER TABLE [DBO].[PRODUTOR] CHECK CONSTRAINT [C_PRODUTOR_DS_TELEFONE]
GO

ALTER TABLE [DBO].[PRODUTOR]  WITH CHECK ADD  CONSTRAINT [C_PRODUTOR_DS_EMAIL] CHECK  ([DS_EMAIL] LIKE '%@%')
GO

ALTER TABLE [DBO].[PRODUTOR] CHECK CONSTRAINT [C_PRODUTOR_DS_EMAIL]
GO

ALTER TABLE [DBO].[PRODUTOR] WITH CHECK ADD CONSTRAINT [C_PRODUTOR_DS_CEP] CHECK ((NOT [DS_CEP] LIKE '%[^0-9]%') AND (DATALENGTH([DS_CEP]) = 8))
GO

ALTER TABLE [DBO].[PRODUTOR] CHECK CONSTRAINT [C_PRODUTOR_DS_CEP]
GO

ALTER TABLE [DBO].[PRODUTOR] WITH CHECK ADD CONSTRAINT [C_PRODUTOR_DT_NASCIMENTO] CHECK (NOT [DT_NASCIMENTO] >= GETDATE())
GO

ALTER TABLE [DBO].[PRODUTOR] CHECK CONSTRAINT [C_PRODUTOR_DT_NASCIMENTO]
GO

ALTER TABLE [DBO].[PRODUTOR]  WITH CHECK ADD  CONSTRAINT [C_PRODUTOR_DS_INSCRICAOFEDERAL] CHECK  ((DATALENGTH([DS_INSCRICAOFEDERAL])=(11) OR DATALENGTH([DS_INSCRICAOFEDERAL])=(16)))
GO

ALTER TABLE [DBO].[PRODUTOR] CHECK CONSTRAINT [C_PRODUTOR_DS_INSCRICAOFEDERAL]
GO