	USE [DBHORTI]
GO

/****** OBJECT:  TABLE [DBO].[UNIDADE]    SCRIPT DATE: 23/10/2019 22:14:23 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

EXEC P_REMOVE_FK N'UNIDADE'
GO

IF OBJECT_ID('DBO.UNIDADE', 'U') IS NOT NULL
	DROP TABLE DBO.UNIDADE;

CREATE TABLE [DBO].[UNIDADE](
	[ID_UNIDADE] [UNIQUEIDENTIFIER] NOT NULL,
	[DS_NOME] [VARCHAR](50) NULL,
	[BO_ATIVO] [BIT] NOT NULL,
	[DT_CADASTRO] [DATETIME2](3) NOT NULL,
	[DT_ATUALIZACAO] [DATETIME2](3) NOT NULL,
 CONSTRAINT [PK_UNIDADE] PRIMARY KEY CLUSTERED 
(
	[ID_UNIDADE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [DBO].[UNIDADE] ADD  CONSTRAINT [C_UNIDADE_ATIVO]  DEFAULT ((1)) FOR [BO_ATIVO]
GO

ALTER TABLE [DBO].[UNIDADE] ADD  CONSTRAINT [C_UNIDADE_DT_CADASTRO]  DEFAULT (GETDATE()) FOR [DT_CADASTRO]
GO

ALTER TABLE [DBO].[UNIDADE] ADD  CONSTRAINT [C_UNIDADE_DT_ATUALIZACAO]  DEFAULT (GETDATE()) FOR [DT_ATUALIZACAO]
GO