USE DBHORTI
GO

--ROLLBACK
--COMMIT
BEGIN TRAN

INSERT UNIT (DS_UNIT, DS_ABREVIATION, DT_CREATION) VALUES('DUZIA', 'DZ', GETDATE())
INSERT UNIT (DS_UNIT, DS_ABREVIATION, DT_CREATION) VALUES('DEZENA', 'DEZ', GETDATE())
INSERT UNIT (DS_UNIT, DS_ABREVIATION, DT_CREATION) VALUES('UNIDADE', 'UN', GETDATE())
INSERT UNIT (DS_UNIT, DS_ABREVIATION, DT_CREATION) VALUES('METRO', 'MT', GETDATE())
INSERT UNIT (DS_UNIT, DS_ABREVIATION, DT_CREATION) VALUES('TONLEADA', 'TON', GETDATE())
INSERT UNIT (DS_UNIT, DS_ABREVIATION, DT_CREATION) VALUES('QUILOGRAMA', 'KG', GETDATE())
INSERT UNIT (DS_UNIT, DS_ABREVIATION, DT_CREATION) VALUES('LITRO', 'LT', GETDATE())