USE DBHORTI
GO

--COMMIT
--ROLLBACK
BEGIN TRAN 

	INSERT DISTRICT VALUES (NEWID(), 'BARRA FUNDA', GETDATE(), GETDATE())
	INSERT DISTRICT VALUES (NEWID(), 'JABAQUARA', GETDATE(), GETDATE())
	INSERT DISTRICT VALUES (NEWID(), 'CAMPOS ELÍSEOS', GETDATE(), GETDATE())
	INSERT DISTRICT VALUES (NEWID(), 'BOM RETIRO', GETDATE(), GETDATE())
	INSERT DISTRICT VALUES (NEWID(), 'PARAÍSO', GETDATE(), GETDATE())
	INSERT DISTRICT VALUES (NEWID(), 'CONSOLAÇÃO', GETDATE(), GETDATE())
	INSERT DISTRICT VALUES (NEWID(), 'PINHEIROS', GETDATE(), GETDATE())
	