USE [DBHORTI]
GO

/****** OBJECT:  TABLE [DBO].[CITY]    SCRIPT DATE: 23/10/2019 22:59:01 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

EXEC P_REMOVE_FK N'CITY'
GO

IF OBJECT_ID('DBO.CITY', 'U') IS NOT NULL
	DROP TABLE DBO.CITY;

CREATE TABLE [DBO].[CITY](
	[ID_CITY] [INT] NOT NULL,
	[ID_COUNTRY] [VARCHAR](5) NOT NULL,
	[ID_STATE] [INT] NOT NULL,
	[DS_CITY] [NVARCHAR](200) NULL,
	[CD_CITY] [VARCHAR](5) NULL,
 CONSTRAINT [PK_CITY] PRIMARY KEY CLUSTERED 
(
	[ID_CITY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [DBO].[CITY]  WITH CHECK ADD  CONSTRAINT [FK_CITY_STATE] FOREIGN KEY([ID_COUNTRY], [ID_STATE])
REFERENCES [DBO].[STATE] ([ID_COUNTRY], [ID_STATE])
GO

ALTER TABLE [DBO].[CITY] CHECK CONSTRAINT [FK_CITY_STATE]
GO