USE [DBHORTI]
GO

/****** OBJECT:  TABLE [DBO].[CLIENT]    SCRIPT DATE: 07/12/2019 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

EXEC P_REMOVE_FK N'CLIENT'
GO

IF OBJECT_ID('DBO.CLIENT', 'U') IS NOT NULL
	DROP TABLE DBO.CLIENT;

CREATE TABLE [DBO].[CLIENT](
	[ID_CLIENT] [UNIQUEIDENTIFIER] NOT NULL,
	[DS_EMAIL] [NVARCHAR](40) NOT NULL,
	[DS_CLIENT] [NVARCHAR](100) NOT NULL,
	[BO_ACTIVE] [BIT] NOT NULL,
	[DT_CREATION] [DATETIME2](3) NOT NULL,
	[DT_ATUALIZATION] [DATETIME2](3) NOT NULL,
	[ID_CITY] [INT] NULL,
	[ID_DISTRICT] [UNIQUEIDENTIFIER] NULL,
	[DS_PHONE] [VARCHAR](11) NULL,
	[DS_FEDERALINSCRIPTION] [VARCHAR](16) NULL,
	CONSTRAINT [PK_CLIENT] PRIMARY KEY	( [ID_CLIENT], [DS_EMAIL] ASC)

	WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [DBO].[CLIENT] ADD  CONSTRAINT [C_CLIENT_ACTIVE]  DEFAULT 1 FOR [BO_ACTIVE]
GO

ALTER TABLE [DBO].[CLIENT] ADD  CONSTRAINT [C_CLIENT_DT_ATUALIZATION]  DEFAULT GETDATE() FOR [DT_ATUALIZATION]
GO

ALTER TABLE [DBO].[CLIENT]  WITH CHECK ADD  CONSTRAINT [FK_CLIENT_USERHORTI] FOREIGN KEY([DS_EMAIL])
REFERENCES [DBO].[USERHORTI] ([DS_LOGIN])
GO

ALTER TABLE [DBO].[CLIENT] CHECK CONSTRAINT [FK_CLIENT_USERHORTI]
GO

ALTER TABLE [DBO].[CLIENT]  WITH CHECK ADD  CONSTRAINT [FK_CLIENT_CITY] FOREIGN KEY([ID_CITY])
REFERENCES [DBO].[CITY] ([ID_CITY])
GO

ALTER TABLE [DBO].[CLIENT] CHECK CONSTRAINT [FK_CLIENT_CITY]
GO

ALTER TABLE [DBO].[CLIENT]  WITH CHECK ADD  CONSTRAINT [FK_CLIENT_DISTRICT] FOREIGN KEY([ID_DISTRICT])
REFERENCES [DBO].[DISTRICT] ([ID_DISTRICT])
GO

ALTER TABLE [DBO].[CLIENT] CHECK CONSTRAINT [FK_CLIENT_DISTRICT]
GO

ALTER TABLE [DBO].[CLIENT]  WITH CHECK ADD  CONSTRAINT [C_CLIENT_DS_PHONE] CHECK  ((NOT [DS_PHONE] LIKE '%[^0-9]%') AND (DATALENGTH([DS_PHONE]) = 10 OR DATALENGTH([DS_PHONE]) = 11))
GO

ALTER TABLE [DBO].[CLIENT] CHECK CONSTRAINT [C_CLIENT_DS_PHONE]
GO

ALTER TABLE [DBO].[CLIENT]  WITH CHECK ADD  CONSTRAINT [C_CLIENT_DS_EMAIL] CHECK  (([DS_EMAIL] LIKE '%@%') AND ([DS_EMAIL] LIKE '%.com%'))
GO

ALTER TABLE [DBO].[CLIENT] CHECK CONSTRAINT [C_CLIENT_DS_EMAIL]
GO

ALTER TABLE [DBO].[CLIENT]  WITH CHECK ADD  CONSTRAINT [C_CLIENT_DS_FEDERALINSCRIPTION] CHECK  ((DATALENGTH([DS_FEDERALINSCRIPTION])=(11) OR DATALENGTH([DS_FEDERALINSCRIPTION])=(16)))
GO

ALTER TABLE [DBO].[CLIENT] CHECK CONSTRAINT [C_CLIENT_DS_FEDERALINSCRIPTION]
GO