USE [DBHORTI]
GO

/****** OBJECT:  TABLE [DBO].[COUNTRY]    SCRIPT DATE: 23/10/2019 22:57:33 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

EXEC P_REMOVE_FK N'COUNTRY'
GO

IF OBJECT_ID('DBO.COUNTRY', 'U') IS NOT NULL
	DROP TABLE DBO.COUNTRY;

CREATE TABLE [DBO].[COUNTRY](
	[ID_COUNTRY] [VARCHAR](5) NOT NULL,
	[DS_COUNTRY] [NVARCHAR](200) NULL,
 CONSTRAINT [PK_COUNTRY] PRIMARY KEY CLUSTERED 
(
	[ID_COUNTRY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO