USE [DBHORTI]
GO

/****** OBJECT:  TABLE [DBO].[LOG]    SCRIPT DATE: 09/01/2020  ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

EXEC P_REMOVE_FK N'LOG'
GO

IF OBJECT_ID('DBO.LOG', 'U') IS NOT NULL
	DROP TABLE DBO.LOG;

CREATE TABLE [DBO].[LOG](
	[ID_LOG] [UNIQUEIDENTIFIER] NOT NULL,
	[DS_USERLOG] [NVARCHAR](50) NOT NULL,
	[DS_INFOLOG] [VARCHAR](MAX) NOT NULL,
	[CD_LEVELLOG] [VARCHAR](10) NOT NULL,
	[DT_CREATION] [DATETIME2](3) NOT NULL,
	CONSTRAINT [PK_LOG] PRIMARY KEY CLUSTERED	(	[ID_LOG] ASC	)

	WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [DBO].[LOG] ADD  CONSTRAINT [C_LOG_DT_CREATION]  DEFAULT (GETDATE()) FOR [DT_CREATION]
GO