USE [DBHORTI]
GO

/****** OBJECT:  TABLE [DBO].[USERHORTI]    SCRIPT DATE: 07/12/2019  ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

EXEC P_REMOVE_FK N'USERHORTI'
GO

IF OBJECT_ID('DBO.USERHORTI', 'U') IS NOT NULL
	DROP TABLE DBO.USERHORTI;

CREATE TABLE [DBO].[USERHORTI](
	[DS_LOGIN] [NVARCHAR](40) NOT NULL,
	[DS_PASSWORD] [NVARCHAR](100) NOT NULL,
	[BO_ACTIVE] [BIT] NOT NULL,
	[DT_CREATION] [DATETIME2](3) NOT NULL,
	[DT_ATUALIZATION] [DATETIME2](3) NOT NULL,
 CONSTRAINT [PK_USERHORTI] PRIMARY KEY CLUSTERED 
(
	[DS_LOGIN] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [DBO].[USERHORTI] ADD  CONSTRAINT [C_USERHORTI_ACTIVE]  DEFAULT ((1)) FOR [BO_ACTIVE]
GO

ALTER TABLE [DBO].[USERHORTI] ADD  CONSTRAINT [C_USERHORTI_DT_CREATION]  DEFAULT (GETDATE()) FOR [DT_CREATION]
GO

ALTER TABLE [DBO].[USERHORTI] ADD  CONSTRAINT [C_USERHORTI_DT_ATUALIZATION]  DEFAULT (GETDATE()) FOR [DT_ATUALIZATION]
GO

ALTER TABLE [DBO].[USERHORTI]  WITH CHECK ADD  CONSTRAINT [C_USERHORTI_PASSWORD] CHECK (([DS_PASSWORD] LIKE '%[0-9]%') AND ([DS_PASSWORD] LIKE '%[a-z]%') 
		AND ([DS_PASSWORD] LIKE '%[A-Z]%') AND ([DS_PASSWORD] LIKE '%[^a-zA-Z0-9]%') AND (DATALENGTH([DS_PASSWORD]) >= 8))
GO

ALTER TABLE [DBO].[USERHORTI] CHECK CONSTRAINT [C_USERHORTI_PASSWORD]
GO

ALTER TABLE [DBO].[USERHORTI]  WITH CHECK ADD  CONSTRAINT [C_USERHORTI_LOGIN] CHECK  (([DS_LOGIN] LIKE '%@%') AND ([DS_LOGIN] LIKE '%.com%'))
GO

ALTER TABLE [DBO].[USERHORTI] CHECK CONSTRAINT [C_USERHORTI_LOGIN]
GO