USE [DBHORTI]
GO

/****** OBJECT:  TABLE [DBO].[DISTRICT]    SCRIPT DATE: 23/10/2019 22:59:59 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

EXEC P_REMOVE_FK N'DISTRICT'
GO

IF OBJECT_ID('DBO.DISTRICT', 'U') IS NOT NULL
	DROP TABLE DBO.DISTRICT;

CREATE TABLE [DBO].[DISTRICT](
	[ID_DISTRICT] [UNIQUEIDENTIFIER] NOT NULL,
	[DS_NAME] [VARCHAR](50) NULL,
	[BO_ACTIVE] [BIT] NOT NULL CONSTRAINT [C_DISTRICT_ACTIVE]  DEFAULT ((1)),
	[DT_CREATION] [DATETIME2](3) NOT NULL CONSTRAINT [C_DISTRICT_DT_CREATION]  DEFAULT (GETDATE()),
	[DT_ATUALIZATION] [DATETIME2](3) NOT NULL CONSTRAINT [C_DISTRICT_DT_ATUALIZATION]  DEFAULT (GETDATE()),
 CONSTRAINT [PK_DISTRICT] PRIMARY KEY CLUSTERED 
(
	[ID_DISTRICT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO