USE [DBHORTI]
GO

/****** OBJECT:  TABLE [DBO].[UNITY]    SCRIPT DATE: 23/10/2019 22:14:23 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

EXEC P_REMOVE_FK N'UNITY'
GO

IF OBJECT_ID('DBO.UNITY', 'U') IS NOT NULL
	DROP TABLE DBO.UNITY;

CREATE TABLE [DBO].[UNITY](
	[ID_UNITY] [UNIQUEIDENTIFIER] NOT NULL,
	[DS_NAME] [VARCHAR](50) NULL,
	[BO_ACTIVE] [BIT] NOT NULL,
	[DT_CREATION] [DATETIME2](3) NOT NULL,
	[DT_ATUALIZATION] [DATETIME2](3) NOT NULL,
 CONSTRAINT [PK_UNITY] PRIMARY KEY CLUSTERED 
(
	[ID_UNITY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [DBO].[UNITY] ADD  CONSTRAINT [C_UNITY_ACTIVE]  DEFAULT ((1)) FOR [BO_ACTIVE]
GO

ALTER TABLE [DBO].[UNITY] ADD  CONSTRAINT [C_UNITY_DT_CREATION]  DEFAULT (GETDATE()) FOR [DT_CREATION]
GO

ALTER TABLE [DBO].[UNITY] ADD  CONSTRAINT [C_UNITY_DT_ATUALIZATION]  DEFAULT (GETDATE()) FOR [DT_ATUALIZATION]
GO