USE [DBHORTI]
GO

/****** OBJECT:  STOREDPROCEDURE [DBO].[P_REMOVE_FK]    SCRIPT DATE: 23/10/2019 23:13:55 DN-WASATAIN ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [DBO].[P_REMOVE_FK] 
	@DS_TABELA NVARCHAR(50) = NULL
AS
BEGIN
	SET NOCOUNT ON;
	DECLARE @STMT VARCHAR(300);

	DECLARE CUR CURSOR FOR
    SELECT 'ALTER TABLE ' + OBJECT_SCHEMA_NAME(PARENT_OBJECT_ID) + '.' + OBJECT_NAME(PARENT_OBJECT_ID) +
                    ' DROP CONSTRAINT ' + NAME
    FROM SYS.FOREIGN_KEYS 
	WHERE OBJECT_SCHEMA_NAME(REFERENCED_OBJECT_ID) = 'DBO' AND 
		  OBJECT_NAME(REFERENCED_OBJECT_ID) = @DS_TABELA;
 
   OPEN CUR;
   FETCH CUR INTO @STMT;
 
   -- DROP EACH FOUND FOREIGN KEY CONSTRAINT 
   WHILE @@FETCH_STATUS = 0
		BEGIN
			EXEC (@STMT);
			FETCH CUR INTO @STMT;
		END
 
	CLOSE CUR;
	DEALLOCATE CUR;
END

GO